backend: 
  name: github
  repo: lamencha/atozeatsblog

media_folder: static/assets
public_folder: /assets

collections: 
  - name: post
    label: Posts
    folder: src/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Create At, widget: date }
      - { name: body, label: Post, widget: markdown }
      - { name: cream, label: Cream of the Crop 1 to add 2 to omit, widget: number, valueType: int}
      - { name: top, label: Top Places 1 to add 2 to omit, widget: number, valueType: int }
      - { name: new1, label: New Places 1 to add 2 to omit, widget: number, valueType: int}
      - { name: image, label: Image name one word or nameCase, widget: image }