backend: 
  name: github
  repo: lamencha/atozeatsblog

media_folder: static/assets


collections: 
  - name: post
    label: Posts
    folder: src/posts
    create: true
    fields:
      - { name: title, label: Title }
      - { name: date, label: Create At, widget: date }
      - { name: body, label: Post, widget: markdown }
      - { name: cream, label: Cream of the Crop true to add false to omit }
      - { name: top, label: Top Places true to add false to omit, widget }
      - { name: new1, label: New Places true to add false to omit }